#!/bin/bash

echo "🔍 Checking SSL Certificate Status"
echo "=================================="
echo ""

# Check if certificate exists
if [ -f "/etc/letsencrypt/live/family.bananas4life.com/fullchain.pem" ]; then
    echo "✅ SSL certificate found!"
    echo "📅 Certificate details:"
    sudo openssl x509 -in /etc/letsencrypt/live/family.bananas4life.com/fullchain.pem -text -noout | grep -E "(Subject:|Not After)"
    echo ""
    echo "🚀 Ready to complete SSL setup!"
    echo "Run: curl -fsSL https://raw.githubusercontent.com/zanijr/WebApp/main/complete-ssl-setup.sh | bash"
else
    echo "❌ SSL certificate not found"
    echo ""
    echo "🔧 EASIEST SOLUTION: Use Cloudflare SSL"
    echo "======================================"
    echo ""
    echo "Since Let's Encrypt is having issues with your Cloudflare setup,"
    echo "the simplest solution is to use Cloudflare's free SSL:"
    echo ""
    echo "1. Go to https://dash.cloudflare.com"
    echo "2. Select 'bananas4life.com' domain"
    echo "3. Click 'SSL/TLS' in left menu"
    echo "4. Set encryption mode to 'Full (strict)'"
    echo "5. Go to 'SSL/TLS' > 'Edge Certificates'"
    echo "6. Turn ON 'Always Use HTTPS'"
    echo ""
    echo "✅ This will instantly enable HTTPS for your domain!"
    echo "✅ No server configuration needed!"
    echo "✅ Cloudflare manages the certificate automatically!"
    echo ""
    echo "🌐 After enabling Cloudflare SSL:"
    echo "   https://family.bananas4life.com will work immediately"
    echo ""
    echo "🔧 ALTERNATIVE: Try Let's Encrypt again"
    echo "======================================"
    echo ""
    echo "If you prefer your own certificate, you can try:"
    echo ""
    echo "1. Temporarily disable Cloudflare proxy:"
    echo "   - Go to Cloudflare DNS settings"
    echo "   - Click the orange cloud next to 'family' record"
    echo "   - Change it to 'DNS only' (gray cloud)"
    echo "   - Wait 5 minutes"
    echo ""
    echo "2. Run SSL setup again:"
    echo "   cd /home/zbonham/WebApp"
    echo "   git pull origin main"
    echo "   chmod +x setup-ssl-cloudflare.sh"
    echo "   ./setup-ssl-cloudflare.sh"
    echo ""
    echo "3. Re-enable Cloudflare proxy after SSL is working"
    echo ""
fi

echo ""
echo "🎯 RECOMMENDATION: Use Cloudflare SSL"
echo "===================================="
echo ""
echo "Cloudflare SSL is:"
echo "✅ Easier to set up (2 minutes)"
echo "✅ Automatically managed"
echo "✅ Better performance with CDN"
echo "✅ No server maintenance needed"
echo ""
echo "Your Family Chores app is already working perfectly with HTTP."
echo "Adding Cloudflare SSL will make it secure with HTTPS instantly!"
