#!/bin/bash

# Simple SSL Setup for Family Chores App with Cloudflare
# This script provides clear instructions for enabling HTTPS

echo "🔒 SSL Setup for Family Chores App"
echo "=================================="
echo ""
echo "Since you're using Cloudflare, the EASIEST way to enable HTTPS is:"
echo ""
echo "🌟 CLOUDFLARE SSL (RECOMMENDED)"
echo "==============================="
echo ""
echo "1. Go to https://dash.cloudflare.com"
echo "2. Select your 'bananas4life.com' domain"
echo "3. Click on 'SSL/TLS' in the left menu"
echo "4. Set SSL/TLS encryption mode to 'Full (strict)'"
echo "5. Go to 'SSL/TLS' > 'Edge Certificates'"
echo "6. Turn ON 'Always Use HTTPS'"
echo ""
echo "That's it! After these steps:"
echo "✅ https://family.bananas4life.com will work automatically"
echo "✅ HTTP will redirect to HTTPS"
echo "✅ SSL certificate managed by Cloudflare"
echo "✅ No server configuration needed"
echo ""
echo "🔧 ALTERNATIVE: Let's Encrypt (Advanced)"
echo "========================================"
echo ""
echo "If you prefer your own SSL certificate, run:"
echo "cd /home/zbonham/WebApp"
echo "git pull origin main"
echo "chmod +x setup-ssl-cloudflare.sh"
echo "./setup-ssl-cloudflare.sh"
echo ""
echo "Then choose option 2 and follow the prompts."
echo ""
echo "🎯 RECOMMENDATION"
echo "================"
echo ""
echo "Use Cloudflare SSL (option 1) because:"
echo "✅ Zero server setup required"
echo "✅ Works immediately"
echo "✅ Automatic certificate management"
echo "✅ Better performance with Cloudflare's CDN"
echo ""
echo "After enabling Cloudflare SSL, test your site:"
echo "🔒 https://family.bananas4life.com"
echo ""
echo "Your Family Chores app will be fully secure!"
